name: memorize
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# develop
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  uuid: ^4.5.0
  webview_flutter: ^4.9.0
  dropdown_button2: ^2.3.9

# design
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  swipable_stack: ^2.0.0
  smooth_page_indicator: ^1.2.0+3
  lottie: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  change_app_package_name: ^1.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
